// react/src/app/components/two-way-binding/two-way-binding.tsx
'use client'
import { useState } from 'react'
import AppCounter from './counter'

const AppTwoWayBinding = () => {
  const [firstCount, firstCountChange] = useState<number>(0)

  return (
    <>
      <h4>Two-way binding</h4>

      <p>Parent `firstCount` state: {firstCount}</p>

      <AppCounter firstCount={firstCount} firstCountChange={firstCountChange} />
    </>
  )
}

export default AppTwoWayBinding

// angular/src/app/components/two-way-binding/two-way-binding.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import { CounterComponent } from './counter/counter.component'

@Component({
  selector: 'app-two-way-binding',
  standalone: true,
  imports: [CommonModule, CounterComponent],
  templateUrl: './two-way-binding.component.html'
})
export class TwoWayBindingComponent {
  firstCount = 0
  secondCount = 0
}

<h4>Two-way binding</h4>

<p>Parent `firstCount` state: {{ firstCount }}</p>
<p>Parent `secondCount` state: {{ secondCount }}</p>

<app-counter
  [(firstCount)]="firstCount"
  [secondCount]="secondCount"
  (secondCountChange)="secondCount = $event"
/>
