// react/src/app/components/input/input.tsx
'use client'
import { useState } from 'react'
import AppCounter from './counter'

const AppInput = () => {
  let [count, setCount] = useState(0)
  const handleIncrement = (): void => {
    setCount(++count)
  }

  return (
    <>
      <h4>Input</h4>

      <AppCounter count={count} />
      <button onClick={handleIncrement}>Increment</button>
    </>
  )
}

export default AppInput

// angular/src/app/components/input/input.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import { CounterComponent } from './counter/counter.component'

@Component({
  selector: 'app-input',
  standalone: true,
  imports: [CommonModule, CounterComponent],
  templateUrl: './input.component.html'
})
export class InputComponent {
  count = 0

  handleIncrement(): void {
    this.count++
  }
}

<h4>Input</h4>

<app-counter [count]="count" />
<button (click)="handleIncrement()">Increment</button>
