// react/src/app/components/ng-switch.tsx
const AppNgSwitch = () => {
  let id: number
  id = 2

  return (
    <>
      <h4>NgSwitch</h4>

      <p>
        Hi&nbsp;
        {(() => {
          switch (id) {
            case 1:
              return 'Kaylee'
            case 2:
              return 'Maeve'
            case 3:
              return 'Summer'
            default:
              return 'there'
          }
        })()}
      </p>
    </>
  )
}

export default AppNgSwitch

// angular/src/app/components/ng-switch/ng-switch.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-ng-switch',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './ng-switch.component.html'
})
export class NgSwitchComponent {
  id = 2
}

<h4>NgSwitch</h4>

<p>
  Hi
  <ng-container [ngSwitch]="id">
    <ng-container *ngSwitchCase="1">Kaylee</ng-container>
    <ng-container *ngSwitchCase="2">Maeve</ng-container>
    <ng-container *ngSwitchCase="3">Summer</ng-container>
    <ng-container *ngSwitchDefault>there</ng-container>
  </ng-container>
</p>
