// react/src/app/components/two-way-binding/counter.tsx
import { Dispatch, SetStateAction } from 'react'

const AppCounter = ({
  firstCount,
  firstCountChange
}: {
  firstCount: number
  firstCountChange: Dispatch<SetStateAction<number>>
}) => {
  const incrementCounter = (): void => {
    firstCountChange(++firstCount)
  }

  return (
    <>
      <p>Child `firstCount` state: {firstCount}</p>

      <button onClick={incrementCounter}>Increment first counter</button>
    </>
  )
}

export default AppCounter

// angular/src/app/components/two-way-binding/counter/counter.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-counter',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './counter.component.html'
})
export class CounterComponent {
  @Input({ required: true }) firstCount: number
  @Output() firstCountChange = new EventEmitter<number>()
  @Input({ required: true }) secondCount: number
  @Output() secondCountChange = new EventEmitter<number>()

  incrementCounter(): void {
    this.firstCountChange.emit(++this.firstCount)
  }

  incrementSecondCount(): void {
    this.secondCountChange.emit(++this.secondCount)
  }
}

<p>Child `firstCount` state: {{ firstCount }}</p>
<p>Child `secondCount` state: {{ secondCount }}</p>

<button (click)="incrementCounter()">Increment first counter</button>
<button (click)="incrementSecondCount()">Increment second counter</button>
