// react/src/app/components/on-changes/on-changes.tsx
'use client'
import { useState } from 'react'
import AppMessage from './message'

const AppOnChanges = () => {
  const [message, setMessage] = useState<string>('Hey')
  const changeMessage = (): void => {
    setMessage("What's up?")
  }

  return (
    <>
      <h4>OnChanges</h4>

      <AppMessage message={message} />
      <button onClick={changeMessage}>Change the message</button>
    </>
  )
}

export default AppOnChanges

// angular/src/app/components/on-changes/on-changes.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import { MessageComponent } from './message/message.component'

@Component({
  selector: 'app-on-changes',
  standalone: true,
  imports: [CommonModule, MessageComponent],
  templateUrl: './on-changes.component.html'
})
export class OnChangesComponent {
  message = 'Hey'

  changeMessage(): void {
    this.message = "What's up?"
  }
}

<h4>OnChanges</h4>

<app-message [message]="message" />
<button (click)="changeMessage()">Change the message</button>
