// react/src/app/components/view-child.tsx
'use client'
import { createRef } from 'react'

const AppViewChild = () => {
  let message = createRef<HTMLDivElement>()

  const changeMessage = (): void => {
    if (message.current) message.current.innerText = 'New message'
  }

  return (
    <>
      <h4>ViewChild</h4>

      <div ref={message}>Message</div>
      <br />
      <button onClick={changeMessage}>Change message</button>
    </>
  )
}

export default AppViewChild

// angular/src/app/components/view-child/view-child.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-view-child',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './view-child.component.html'
})
export class ViewChildComponent {
  @ViewChild('message') message: ElementRef<HTMLDivElement>

  changeMessage(): void {
    this.message.nativeElement.innerText = 'New message'
  }
}

<h4>ViewChild</h4>

<div #message>Message</div>
<br />
<button (click)="changeMessage()">Change message</button>
