// angular/src/app/components/attribute-directive/attribute-directive.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import { ChangeColorDirective } from './change-color.directive'

@Component({
  selector: 'app-attribute-directive',
  standalone: true,
  imports: [CommonModule, ChangeColorDirective],
  templateUrl: './attribute-directive.component.html'
})
export class AttributeDirectiveComponent {}

<h4>Attribute directive</h4>

<button appChangeColor>Change color</button>

// react/src/app/components/attribute-directive/attribute-directive.tsx
'use client'
import { appChangeColor } from './change-color.directive'

const AppAttributeDirective = () => {
  return (
    <>
      <h4>Attribute directive</h4>

      <button ref={(nativeElement) => appChangeColor(nativeElement)}>
        Change color
      </button>
    </>
  )
}

export default AppAttributeDirective
