// react/src/app/components/data-binding.tsx
const AppDataBinding = () => {
  const buttonName = 'take-care-now'
  const disabled = true

  return (
    <>
      <h4>Data binding</h4>

      <button name={`prefix-${buttonName}`} disabled={disabled}>
        Take care now. Bye-bye, then.
      </button>
    </>
  )
}

export default AppDataBinding

// angular/src/app/components/data-binding/data-binding.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-data-binding',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './data-binding.component.html'
})
export class DataBindingComponent {
  buttonName = 'take-care-now'
  disabled = true
}

<h4>Data binding</h4>

<button name="prefix-{{ buttonName }}" [disabled]="disabled">
  Take care now. Bye-bye, then.
</button>
